### ISSUE TITLE
博主能在写详细一点吗？

### ISSUE THREAD

**Issue by yuwojiusi** [wxlite-plus/ez-wxlite#4]
好不容易找到这个文档，很想用，但博主文档能在写的详细一点吗？

**Comment by jack-Lo** [comment]
具体指哪一部分？

**Comment by jack-Lo** [comment]
迟点补充

**Comment by jack-Lo** [comment]
> 能否有一个demo 看到一些简单的调用比如request，实在是新手，看着有点吃力

新增了[wiki](https://github.com/wxlite-plus/ez-wxlite/wiki)，request补充了[使用介绍](https://github.com/wxlite-plus/ez-wxlite/wiki/req#%E4%BD%BF%E7%94%A8)，其他的部分如有不详细的地方可以提出来，我继续补充，月底前若没有新的反馈就我关闭这个issue啦。

**Comment by yuwojiusi** [comment]
好的 谢谢
