### ISSUE TITLE
request的封装：程序自动走登录的流程，然后再发起一遍请求相关问题

### ISSUE THREAD

**Issue by mydzoo** [wxlite-plus/ez-wxlite#6]
```
onShow: function() {
this.getAccountInfo()
},
```
第一次请求是对的，先授权，再请求这个api；但是当再次触发`onShow`的时候，又是走了2次请求。难道只能放在`onLoad`里面吗？

经过测试，必须在获取sessionid的方法再次
let sessionId = wx.getStorageSync('sessionId');

同时// 统一注入约定的header似乎也存在这个问题。

不知道是本身有问题，还是我代码改动导致的问题。

**Comment by jack-Lo** [comment]
不是很明白你的问题。
如果当前登录状态已经过期，而你发起了三个请求，那么第一个请求发出的时候，后面相继发起的请求并不会等第一个请求回来之后才发起，所以三个请求其实是都发出去了。
这时候第一个请求回来了，告诉大家：“这个登录状态过期了，我们得重新登录一下”，于是自顾自得发起了登录流程，所以在这之后发起的请求（第四第五）就会被搁置，等待这个登录完成以后，才发起，避免做无用功。
但是第二和第三个请求在第一个请求回来之前已经发出去了，我们并不能将他们召回，于是他俩算是白跑了一趟，回来准备告诉大家要重新登录的时候，其实大家已经在忙活着登录的事情了。

所以如果你的请求一个放在onLoad，一个放在onShow，onLoad里的请求还没回来，onShow其实就已经发出去了，那这时候会有两次请求，没有毛病，但是这过程只会有一次登录请求发出，不会有两次。

**Comment by mydzoo** [comment]
可能我描述的不是太准确；

tabBar页面：首页，我的

从`首页`进入`我的`页面，默认是需要授权的，由于未登录，先触发`/auth/login`，然后再触发'/account/index'这2个api；这个是没问题的。

然后我选择再次点击进入`首页`；再点击进入`我的`页面

由于是在`onShow`方法中，所以需要再次发起api请求；但是此时依然
```
先触发`/auth/login`，然后再触发'/account/index'这2个api
```
这个就不对了，经过console.log打印此时`let sessionId = wx.getStorageSync('sessionId');`的sessionId依然为空；

**Comment by jack-Lo** [comment]
如果修改了原来的实现，麻烦检查一下这一部分 https://github.com/wxlite-plus/ez-wxlite/blob/4a3e560b272a472e7bb763cadaecaad4ded2f116/client/req/prototype.js#L113，确保auth的时候，login函数被调用，并且更新了sessionId。

**Comment by jack-Lo** [comment]
如果修改了原来的实现，麻烦检查一下这一部分 [login的实现](https://github.com/wxlite-plus/ez-wxlite/blob/4a3e560b272a472e7bb763cadaecaad4ded2f116/client/req/prototype.js#L113)，确保auth的时候，login函数被调用，并且更新了sessionId。

**Comment by mydzoo** [comment]
非常感谢指导，回头看了下这里，虽然没测试，但是好像找到了原因，是我改动的问题；我把：
```
sessionId = newSessionId; // 更新sessionId
```
这句话删掉，导致`sessionId`变量没能再次更新赋值导致的！

**Comment by jack-Lo** [comment]
不客气
